/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreeBranchSplatRouteImport } from './routes/tree/$branch.$'
import { Route as BlobBranchSplatRouteImport } from './routes/blob/$branch.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreeBranchSplatRoute = TreeBranchSplatRouteImport.update({
  id: '/tree/$branch/$',
  path: '/tree/$branch/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlobBranchSplatRoute = BlobBranchSplatRouteImport.update({
  id: '/blob/$branch/$',
  path: '/blob/$branch/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blob/$branch/$': typeof BlobBranchSplatRoute
  '/tree/$branch/$': typeof TreeBranchSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blob/$branch/$': typeof BlobBranchSplatRoute
  '/tree/$branch/$': typeof TreeBranchSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blob/$branch/$': typeof BlobBranchSplatRoute
  '/tree/$branch/$': typeof TreeBranchSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blob/$branch/$' | '/tree/$branch/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blob/$branch/$' | '/tree/$branch/$'
  id: '__root__' | '/' | '/blob/$branch/$' | '/tree/$branch/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlobBranchSplatRoute: typeof BlobBranchSplatRoute
  TreeBranchSplatRoute: typeof TreeBranchSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree/$branch/$': {
      id: '/tree/$branch/$'
      path: '/tree/$branch/$'
      fullPath: '/tree/$branch/$'
      preLoaderRoute: typeof TreeBranchSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blob/$branch/$': {
      id: '/blob/$branch/$'
      path: '/blob/$branch/$'
      fullPath: '/blob/$branch/$'
      preLoaderRoute: typeof BlobBranchSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlobBranchSplatRoute: BlobBranchSplatRoute,
  TreeBranchSplatRoute: TreeBranchSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
