/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreeTreeIdSplatRouteImport } from './routes/tree/$treeId.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreeTreeIdSplatRoute = TreeTreeIdSplatRouteImport.update({
  id: '/tree/$treeId/$',
  path: '/tree/$treeId/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tree/$treeId/$': typeof TreeTreeIdSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tree/$treeId/$': typeof TreeTreeIdSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tree/$treeId/$': typeof TreeTreeIdSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tree/$treeId/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tree/$treeId/$'
  id: '__root__' | '/' | '/tree/$treeId/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TreeTreeIdSplatRoute: typeof TreeTreeIdSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree/$treeId/$': {
      id: '/tree/$treeId/$'
      path: '/tree/$treeId/$'
      fullPath: '/tree/$treeId/$'
      preLoaderRoute: typeof TreeTreeIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TreeTreeIdSplatRoute: TreeTreeIdSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
